### ISSUE TITLE
This is cool.

### ISSUE THREAD

**Issue by idkjs** [phated/reasonable#11]
I have been searching around to see how I could use some jsoo runtime files like you did here to run some code that might work in either jsoo or reason on the web. If you get a second, maybe you can explain generally how something like this is done so I can try it with nodejs. I dont know go so it would have to something else for me. I came across this but its super old and doesnt run -> https://github.com/raphael-proust/nodejs_of_ocaml.

Either way, thanks for sharing.

Peace.

**Comment by phated** [comment]
I'm not sure what you are asking. This project was an experiment (along the lines of what turned to be Deno) of bundling a reason compiler with a JS runtime so you could compile and run reason code.

If you just want to compile reason code to JS, use melange and dune.

**Comment by idkjs** [comment]
Indeed. I was thinking if I could wrap of some of the jsoo code like you did here, I could maybe have the basis for sharing some of the jsoo api outside of jsoo. Thanks for taking the time. Nice work here. Thanks, again.
