### ISSUE TITLE
Remove developer-specific file references

### ISSUE THREAD

**Issue by gladimdim** [phated/reasonable#9]
When I try to run 'reasonable' exec file, I receive such error (MacOS):

➜  reasonable git:(master) pwd
/Users/dgl/projects/reasonable
➜  reasonable git:(master) ./reasonable ./examples/json/Json.re
2018/06/13 11:41:57 stat /Users/phated/go/src/reasonable/runtime/compiler.js: no such file or directory

**Comment by phated** [comment]
@gladimdim I'm not sure what packr was doing wrong but I swapped it out for https://github.com/shurcooL/vfsgen and had my friend test the binary on his machine and the problem seems fixed.  It made the build process a little more complex but I've added a makefile for that.

**Comment by gladimdim** [comment]
Yes, the fresh version now works! I could run my reasons in 2 cases out of 5!

**Comment by phated** [comment]
@gladimdim Nice! Feel free to let me know what things aren't working in the other 3 cases and I'll take a look.
